### ISSUE TITLE
rtl direction didnt work correctly  

### ISSUE THREAD

**Issue by samaremad** [serenity-is/Serenity#5550]
i added Arabic language and translate the dashboard and when i changed the language to Arabic the dashboard be in Arabic but when i press on any link in dashboard it display that page in English version how can i solve this issue

**Comment by VictorTomaili** [comment]
Did you tried https://serenity.is/demo with farsi language? its has right to left layout and works without problem. I see your question is already in discussions. And there is no answer as well. So may be you need provide more details and share your code there. Not need to create a issue. 
I close this because it's not a serenity issue. Thank you for understanding.

**Comment by obaidalrushdi** [comment]
Hi,
i got same issues 
the demo is work fine . i think because using serenity mvc also we download move tutorial project it work fine but in serenity core 5 it not work also when select Arabic the page return to English language directly
