### ISSUE TITLE
.net 5 UserAccessor.User.GetIdentifier() cause error when login via openId

### ISSUE THREAD

**Issue by minhhungit** [serenity-is/Serenity#5608]
- Serenity .net 5 version

When we login using openId (azure AD), [NameIdentifier](https://github.com/serenity-is/Serenity/blob/9e28e41ee4657d19ea57468a225390350285aef3/src/Serenity.Net.Core/Authorization/AuthorizationExtensions.cs#L68) claim returns "not-number" string so [Convert.ToInt32](https://github.com/serenity-is/Serene/blob/ea6e7581fa4043041d3db2b2bacab786a63d31ff/Serene/Serene.Core/Modules/Administration/User/Authentication/PermissionService.cs#L52) is not correct anymore

Normally value for `NameIdentifier `claim is from `Serenity.dbo.Users.UserID`

![image](https://user-images.githubusercontent.com/2279508/113757136-77487000-973c-11eb-8b86-fefb0fcc4422.png)

**Workarounds solution**: use `UserRetrieveService.ByUsername`

```csharp
var user = (UserDefinition)UserRetrieveService.ByUsername(username);
            
int userId = 0;
if (user != null)
{
    userId = int.Parse(user.Id);
}

if (userId == 0)
{
    userId = Convert.ToInt32(UserAccessor.User.GetIdentifier(), CultureInfo.InvariantCulture);
}
```

**Comment by VictorTomaili** [comment]
When you use different auth provider than serenity has own, you need implement own `PermissionService`, `UserRetrieveService` etc. if it's causes errors. You can replace them [there](https://github.com/serenity-is/Serene/blob/master/Serene/Serene.Core/Initialization/Startup.cs#L127)
Serenity has `Int32` id field and it's sets `Int32` value there while creating principal. So expected behavior is converting to Int32 not causes error. For custom implementations like yours, needs some extra implementations what currently doesn't included by default. 
OpenID implementation is welcome as pull request.

**Comment by minhhungit** [comment]
yes but problem is `GetIdentifier` method can be used in somewhere else and hardcode so I just worry that we can not use DI way.
Currently I just see we use the method in `PermissionService.cs` (sure we can implement a custom version of PermissionService and registry it using DI like you said), but not sure if in future we will use the method in somewhere. So I guess better way we should update `GetIdentifier` method

Do you think it's okay if we update the method like this:

```csharp
public static string GetIdentifier(this ClaimsPrincipal identity)
{
    if (identity == null)
        return null;

    // check IsLoggedIn
    if (!IsLoggedIn(identity))
        return null;
    
    // firstly, try to get user info by username
    var user = (TUserDefinition)userRetrieveService.ByUsername(identity.Identity.Name);
    if (user != null) 
    {
        return user.UserId;
    }

    // get userId from claim
    return identity.FindFirst(ClaimTypes.NameIdentifier)?.Value;
}
```

**Comment by VictorTomaili** [comment]
Are you point to [this](https://github.com/serenity-is/Serenity/blob/master/src/Serenity.Net.Core/Authorization/AuthorizationExtensions.cs#L68) method? 

This method doesn't interest about type of name identifier. It's always string there. It's implemented by `System.Security.Claims.Claim` class from Microsoft self. Not related to Serenity.

When you have ClaimsPrincipal, you must get identifier from there. Because It's already filled from database. Your code brings to one more query. Also both of value is returned as String and same value. 

Your exception occurs on `PermissionService` implementation, what expects `GetIdentifier` method returns an integer. 

I move this issue to Discussion.
