### ISSUE TITLE
[ScriptInclude] does not generate classes

### ISSUE THREAD

**Issue by fwd079** [serenity-is/Serenity#5652]
Good afternoon,

**Describe the bug**
`[ScriptInclude]` does not generate classes properly.

**To Reproduce**
```charp
[ScriptInclude]
public class MyClass
{
 public Row MyRow {get; set;}
}
```

**Expected behavior**
```typescript
export class MyClass{
    MyRow?: Row;
}
```

**Current behavior**
```typescript
export interface MyClass{}
```

**Additional context**
Add any other context about the problem here. - This [shot in the dark](https://github.com/serenity-is/Serenity/issues/5241) doesn't work and was asked to create a new one, so here we are. lol

But was wondering, was `ScriptIncludeAttribute` really meant to generate classes at all?

Kind Regards.

**Comment by VictorTomaili** [comment]
I kindly asked for using discussion instead issues.  
Also I tried on latest template with latest code generation tool. It's working as expected. 

![image](https://user-images.githubusercontent.com/2023440/115590626-dc25cd80-a2d9-11eb-9f2c-f4aec641bc3f.png)

**Comment by fwd079** [comment]
Oh interesting, okay will inform the client that latest upgrade resolves the issue. Tested myself and cofirmed.

Well I've been working on and promoting `Serenity` for past two years now, so felt kind of rude to shut the door on other thread. But you did it once again, without waiting for my reply. 🙂

Thanks for looking into it anyway, will inform client.

**Comment by VictorTomaili** [comment]
Hello @fwd079,
I'm trying to be kind. I asking kindly for use correct way to solve your problem. I wrote an answer about open a "[discussion](https://github.com/serenity-is/Serenity/discussions)" and you just open another "issue" instead use "discussion". Also you firstly wrote on old issue. When you wrote there, It's notified too much people who doesn't interested about your problem. And I close that issue for comments because of it.

Also when you try to open an new issue you must faced this. 
![image](https://user-images.githubusercontent.com/2023440/115694435-84cf3e00-a369-11eb-96d3-5ce8f1065ee9.png)

And also bug report needs too many information about bug. You need to fill all of them for reproduce and accept it as an issue. 

![image](https://user-images.githubusercontent.com/2023440/115694606-b21bec00-a369-11eb-96e0-158b5d08e380.png)
