### ISSUE TITLE
UtilityEXEPath Cannot be Null

### ISSUE THREAD

**Issue by mrajalko** [serenity-is/Serenity#5653]
- [x] This isn't a feature request or a discussion topic
- [x] I have searched open and closed issues for duplicates
- [x] I am searched documents on https://serenity.is/docs/
- [x] I have read https://serenity.is/docs/startsharp/faq
- [x] I have to use descriptive issue title
- [x] I approve to fill in the information below
 
**Describe the bug**

**To Reproduce**
1. Go to Nothwind->Order
2. Click on Edit Link to edit any order
3. Click On Invoice Button 

**Expected behavior**
A PDF to be opened in a new tab
**Screenshots**

![image](https://user-images.githubusercontent.com/18166582/115723768-ef01d600-a39d-11eb-9037-43d33993372c.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [edge]
 

**Additional context**
wkhtmltopdf.exe is not on any path.

**Comment by VictorTomaili** [comment]
You need to add wkhtmltopdf.exe in your app directory. [Check this lines](https://github.com/serenity-is/Serene/blob/master/Serene/Serene.Core/Modules/Common/Reporting/ReportController.cs#L134)

I close this because this is not a valid issue. if you didn't ensure about It is an bug or not, please prefer discussions instead issues.

**Comment by obaidalrushdi** [comment]
Hi 
i have same because i miss wkhtmltopdf.exe 
i found it but where i should put it ?

**Comment by mrajalko** [comment]
please see discussion #5654
