### ISSUE TITLE
Serenity for asp.net core 3.1

### ISSUE THREAD

**Issue by armanarnautovic** [serenity-is/Serenity#5698]
Hello everyone,
I would like to ask kindly if someone can give me an help to solve this problem: I would like to use serenity to realize a management project, however I would not like to do it with .NET 5.0 but with .NET Core 3.1, but installing it from the marketplace for visual studio 2019 remains bound to 5.0.
Unfortunately I can't do otherwise, also I would prefer to do it with 5.0 but I have this need.

Thanks in advance

**Comment by VictorTomaili** [comment]
Hello @armanarnautovic 

I try to navigate users for community support before they try open an issue. Because we didn't want use issues for support etc. Github has a feature named Discussions about Questions & Answers and more. But I guess I missed something. Did you see this page before open an issue?

![image](https://user-images.githubusercontent.com/2023440/117540479-61b6b680-b018-11eb-99a1-acbec6906150.png)
