### ISSUE TITLE
Is there a How to for Serenity Core Reporting Using Telerik Report Html5Viewer ?

### ISSUE THREAD

**Issue by AhmedAbdellah93** [serenity-is/Serenity#5892]
How to for Serenity Core Reporting Using Telerik Report Html5Viewer ?

**Comment by AhmedAbdellah93** [comment]
@VictorTomaili why you close my issuse you doesn't answer me in any of them ?

**Comment by VictorTomaili** [comment]
@AhmedAbdellah93 I already said 2 times, use discussions for questions. Don't use issues for personal questions. There is a [discussion](https://github.com/serenity-is/Serenity/discussions) tab for questions on Github. And if you continue to open issues about this type of question, I will close new issues too. Please be respectful of the rules. Thank you. 
I close this issue too because It's not related to serenity issues and It's duplicated #5890.
