### ISSUE TITLE
inplace button for lookupeditor does not show properly after Serenity.EditorUtils.setReadonly is used

### ISSUE THREAD

**Issue by peterkuijpers** [serenity-is/Serenity#5939]
Hi there,

It seems that some of the inplace button properties for LookupEditor are not set properly after using (in xyzDialog):
`Serenity.EditorUtils.setReadonly( this.form.SupplierId.element, true );`
followed by:
`Serenity.EditorUtils.setReadonly( this.form.SupplierId.element, false );`
 
setReadonly=true sets the opacity of the button to 0.1 and no cursor,  but setReadonly = false does not reset the opacity and the cursor (but the button is working).
Expected behaviour is that setReadonly= false sets the opacity to 1 and cursor is 'default'

Using .net core 3.1
Serenity 3.14.3
Browser GoogleChrome
![bug](https://user-images.githubusercontent.com/498752/130716590-8169e5d7-723c-4d0b-a6e7-136befdd9e73.png)

**Comment by VictorTomaili** [comment]
There is no issue with this. You set the element as read-only. Not widget itself. `setReadonly` is not changed from 3.1 to 5.x it's the same method working with widget types. Use this to manage the widget itself instead of just the widget element.  `Serenity.EditorUtils.setReadonly(this.form.SupplierId, false);`

Please use discussion before this type of issue. If in the discussion, it's decided to this is an issue, then create one with refer discussion. 
Also please read this [announcement ](https://github.com/serenity-is/Serenity/issues/5329)
For .net 3.x versions there is a v3 branch in Serenity, Serene and StartSharp repositories but we will not be releasing any new versions there unless we find a critical security issue or similar. 

![image](https://user-images.githubusercontent.com/2023440/130738620-73b15eb3-bd4c-4d9c-938c-a4eef077152b.png)

![image](https://user-images.githubusercontent.com/2023440/130738660-fe3613d3-9a9d-4371-bd54-b5953933cfb6.png)
