### ISSUE TITLE
[Bug report]: Demo Site Northwind Orders Print Invoice

### ISSUE THREAD

**Issue by marcobisio** [serenity-is/Serenity#7058]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

Print Invoice isn't working properly in demo site (https://demo.serenity.is/Northwind/Order)

### What did you expect to happen?

print the invoice pdf

### How to reproduce?

click on the pdf icon in the Orders grid: https://demo.serenity.is/Northwind/Order

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

demo site

**Comment by furkanevran** [comment]
Hi @marcobisio, thank you for reporting.

I found out that we were searching for an "inline-element" class as a parent of the clicked item (usually the i.fa) instead of an element having the "inline-element" class, sent a [PR](https://github.com/serenity-is/common-features/pull/34) that fixes this issue.

**Comment by marcobisio** [comment]
Thanks!
